BEGIN 
  BEGIN 
  EXECUTE IMMEDIATE 'DROP TABLE OBJTYPE CASCADE CONSTRAINTS';
    EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
      
  BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ATTRTYPE CASCADE CONSTRAINTS';
    EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LISTS CASCADE CONSTRAINTS';
      EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE OBJECTS CASCADE CONSTRAINTS';
      EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ATTRIBUTES CASCADE CONSTRAINTS';
      EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE OBJREFERENCE CASCADE CONSTRAINTS';
      EXCEPTION
  WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      END IF;
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE OBJTYPE (
    OBJECT_TYPE_ID NUMBER(20) NOT NULL,
    PARENT_ID      NUMBER(20),
    NAME           VARCHAR2(200 BYTE) NOT NULL UNIQUE,
    DESCRIPTION    VARCHAR2(1000 BYTE),
    CONSTRAINT PK_OBJTYPE_OBJECT_TYPE_ID PRIMARY KEY (OBJECT_TYPE_ID),
    CONSTRAINT FR_OBJTYPE_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID) ON DELETE CASCADE
)';
  END;

  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ATTRTYPE (
    ATTR_ID         	NUMBER(10) NOT NULL,
    OBJECT_TYPE_ID    	NUMBER(20) NOT NULL,
	OBJECT_TYPE_ID_REF  NUMBER(20),
    NAME            	VARCHAR2(200 BYTE) NOT NULL,
    CONSTRAINT PK_ATTRTYPE_ATTR_ID PRIMARY KEY (ATTR_ID),
    CONSTRAINT FK_ATTRTYPE_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID),
  CONSTRAINT FR_ATTRTYPE_OBJECT_TYPE_ID_REF FOREIGN KEY (OBJECT_TYPE_ID_REF) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
)';
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE LISTS (
    ATTR_ID     	NUMBER(10) NOT NULL,
    LIST_VALUE_ID   NUMBER(10) NOT NULL,
    VALUE       	VARCHAR2(4000) NOT NULL,
    CONSTRAINT PK_LISTS_LIST_VALUE_ID PRIMARY KEY (LIST_VALUE_ID),
    CONSTRAINT FK_LISTS_ATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
)';
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE OBJECTS (
    OBJECT_ID      NUMBER(20) NOT NULL,
    PARENT_ID      NUMBER(20),
    OBJECT_TYPE_ID NUMBER(20) NOT NULL,
    NAME           VARCHAR2(2000 BYTE) NOT NULL,
    DESCRIPTION    VARCHAR2(4000 BYTE),
    CONSTRAINT PK_OBJECTS_OBJECT_ID PRIMARY KEY (OBJECT_ID),
    CONSTRAINT FK_OBJECTS_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OBJECTS_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
)';
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ATTRIBUTES (
    ATTR_ID     	NUMBER(10) NOT NULL,
    OBJECT_ID   	NUMBER(20) NOT NULL,
    VALUE       	VARCHAR2(4000 byte),
    DATE_VALUE    	DATE,
    LIST_VALUE_ID   NUMBER(10),
  CONSTRAINT  PK_ATR_ATTR_ID PRIMARY KEY (ATTR_ID, OBJECT_ID),
    CONSTRAINT  FK_ATR_LIST_VALUE_ID FOREIGN KEY (LIST_VALUE_ID) REFERENCES LISTS(LIST_VALUE_ID) ON DELETE CASCADE,
    CONSTRAINT  FK_ATR_ATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE(ATTR_ID) ON DELETE CASCADE,
    CONSTRAINT  FK_ATR_OBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE
)';
  END;
  
  BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE OBJREFERENCE (
    ATTR_ID   NUMBER(10) NOT NULL,
    REFERENCE NUMBER(20) NOT NULL,
    OBJECT_ID NUMBER(20) NOT NULL,
  CONSTRAINT CON_OBJREFERENCE_PK PRIMARY KEY (ATTR_ID, REFERENCE, OBJECT_ID),
    CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_RATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
)';
  END;
END;
/