package com.netcracker.dao;

import com.netcracker.models.AbstractAutoOperation;
import com.netcracker.models.AutoOperationExpense;
import com.netcracker.models.AutoOperationIncome;

import java.util.Collection;

public interface AutoOperationDao {
    AutoOperationIncome getFamilyIncomeAutoOperation(Integer autoOperationId);

    AutoOperationExpense getFamilyExpenseAutoOperation(Integer autoOperationId);

    AutoOperationIncome getPersonalIncomeAutoOperation(Integer autoOperationId);

    AutoOperationExpense getPersonalExpenseAutoOperation(Integer autoOperationId);

    AutoOperationIncome createFamilyIncomeAutoOperation(AutoOperationIncome autoOperationIncome);

    AutoOperationIncome createPersonalIncomeAutoOperation(AutoOperationIncome autoOperationIncome);

    AutoOperationExpense createFamilyExpenseAutoOperation(AutoOperationExpense autoOperationExpense);

    AutoOperationExpense createPersonalExpenseAutoOperation(AutoOperationExpense autoOperationExpense);

    void deleteAutoOperation(Integer autoOperationId);

    Collection<AbstractAutoOperation> getAllTodayOperations(Integer debitAccountId);

    String CREATE_PERSONAL_INCOME_AO = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 12, 'PERSONAL_INCOME_AO', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (67, OBJECTS_ID_S.CURRVAL /*PERSONAL_INCOME*/, ? /*DAY_OF_MONTH*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (56 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (57 /*CATEGORY*/, OBJECTS_ID_S.CURRVAL, NULL, NULL, ? /*32-36*/) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (58 /*CURRENT_DATE*/, OBJECTS_ID_S.CURRVAL, NULL, TRUNC(CURRENT_DATE), NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) VALUES " +
            "(64, OBJECTS_ID_S.CURRVAL /*EXPENSE_OBJECT_ID*/, ? /*PERSONAL_DEBIT_ACC_OBJECT_ID*/) " + "SELECT * FROM DUAL";

    String CREATE_PERSONAL_EXPENSE_AO = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 11, 'PERSONAL_EXPENSE_AO', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (62, OBJECTS_ID_S.CURRVAL /*PERSONAL_EXPENSE*/, ? /*DAY_OF_MONTH*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (50 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (51 /*CATEGORY*/, OBJECTS_ID_S.CURRVAL, NULL, NULL, ? /*14-18*/) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (52 /*CURRENT_DATE*/, OBJECTS_ID_S.CURRVAL, NULL, TRUNC(CURRENT_DATE), NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (59, OBJECTS_ID_S.CURRVAL /*EXPENSE_OBJECT_ID*/, ? /*PERSONAL_DEBIT_ACC_OBJECT_ID*/) " + "SELECT * FROM DUAL";

    String CREATE_FAMILY_INCOME_AO = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 23, 'FAMILY_INCOME_AO', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (68, OBJECTS_ID_S.CURRVAL /*FAMILY_INCOME*/, ? /*DAY_OF_MONTH*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (56 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (57 /*CATEGORY*/, OBJECTS_ID_S.CURRVAL, NULL, NULL, ? /*32-36*/) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (58 /*CURRENT_DATE*/, OBJECTS_ID_S.CURRVAL, NULL, TRUNC(CURRENT_DATE), NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (65, OBJECTS_ID_S.CURRVAL /*INCOME_OBJECT_ID*/, ? /*FAMILY_DEBIT_ACC_OBJECT_ID*/) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (66 /*TRANSACTION_AUTO_INCOME*/, OBJECTS_ID_S.CURRVAL, ? /*REFERENCE_TO_USER*/) " + "SELECT * FROM DUAL";

    String CREATE_FAMILY_EXPENSE_AO = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 22, 'FAMILY_EXPENSE_AO', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (63, OBJECTS_ID_S.CURRVAL /*FAMILY_EXPENSE*/, ? /*DAY_OF_MONTH*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (50 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (51 /*CATEGORY*/, OBJECTS_ID_S.CURRVAL, NULL, NULL, ? /*14-18*/) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (52 /*CURRENT_DATE*/, OBJECTS_ID_S.CURRVAL, NULL, TRUNC(CURRENT_DATE), NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (60, OBJECTS_ID_S.CURRVAL /*EXPENSE_OBJECT_ID*/, ? /*FAMILY_DEBIT_ACC_OBJECT_ID*/) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (61 /*TRANSACTION_AUTO_EXPENSE*/, OBJECTS_ID_S.CURRVAL, ? /*REFERENCE_TO_USER*/) " + "SELECT * FROM DUAL";

    String DELETE_FROM_OBJECTS = "DELETE FROM OBJECTS WHERE OBJECT_ID = ?";
    String DELETE_FROM_ATTRIBUTES = "DELETE FROM ATTRIBUTES WHERE OBJECT_ID = ?";
    String DELETE_FROM_OBJREFERENCE = "DELETE FROM OBJREFERENCE WHERE OBJECT_ID = ?";

    int personalExpense_user_debit_acc_ref_attr_id_1 = 59;
    int personalExpense_day_of_month_attr_id_3 = 62;
    int personalIncome_user_debit_acc_ref_attr_id_1 = 64;
    int personalIncome_day_of_month_attr_id_3 = 67;

    int familyExpense_family_ref_attr_id_1 = 60;
    int familyExpense_users_ref_attr_id_2 = 61;
    int familyExpense_day_of_month_attr_id_4 = 63;
    int familyIncome_family_ref_attr_id_1 = 65;
    int familyIncome_users_ref_attr_id_2 = 66;
    int familyIncome_day_of_month_attr_id_4 = 68;

    String GET_PERSONAL_AO = "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, " +
            "  USER_DEBIT_ACC.OBJECT_ID AS USER_DEBIT_ACC_ID,  USERS.OBJECT_ID AS USER_ID, " +
            "  EMAIL.VALUE AS EMAIL, USER_NAME.VALUE AS USER_NAME, DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, " +
            "  CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION " +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS USER_DEBIT_ACC, OBJECTS USERS, LISTS, OBJREFERENCE USER_DEBIT_ACC_REF, " +
            "  ATTRIBUTES AMOUNT, " +
            "  ATTRIBUTES CATEGORY, ATTRIBUTES DATES, ATTRIBUTES DAY_OF_MONTH, ATTRIBUTES EMAIL, ATTRIBUTES USER_NAME, " +
            "  OBJREFERENCE USERS_REF " +
            "WHERE USER_DEBIT_ACC_REF.ATTR_ID = ? AND AUTO_OPERATION.OBJECT_ID = ? " +
            "  AND AUTO_OPERATION.OBJECT_ID = USER_DEBIT_ACC_REF.OBJECT_ID " +
            "  AND USER_DEBIT_ACC.OBJECT_ID = USER_DEBIT_ACC_REF.REFERENCE " +
            "  AND USERS.OBJECT_ID = USERS_REF.OBJECT_ID AND USER_DEBIT_ACC.OBJECT_ID = USERS_REF.REFERENCE " +
            "  AND DAY_OF_MONTH.ATTR_ID = ? AND AMOUNT.ATTR_ID = 56 " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND EMAIL.ATTR_ID = 3 AND USER_NAME.ATTR_ID = 5 " +
            "  AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND EMAIL.OBJECT_ID = USERS.OBJECT_ID AND USER_NAME.OBJECT_ID = USERS.OBJECT_ID";

    String GET_FAMILY_AO = "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, " +
            "  FAMILY_DEBIT_ACC.OBJECT_ID AS FAMILY_DEBIT_ACC_ID, " +
            "  USERS.OBJECT_ID AS USER_ID, " +
            "  EMAIL.VALUE AS EMAIL, USER_NAME.VALUE AS USER_NAME, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, " +
            "  CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION " +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS FAMILY_DEBIT_ACC, OBJECTS USERS, LISTS, " +
            "  ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES, ATTRIBUTES DAY_OF_MONTH, ATTRIBUTES EMAIL, " +
            "  ATTRIBUTES USER_NAME, OBJREFERENCE FAMILY_REF, OBJREFERENCE USERS_REF " +
            "WHERE FAMILY_REF.ATTR_ID = ? AND USERS_REF.ATTR_ID = ? " +
            "  AND AUTO_OPERATION.OBJECT_ID = ? " +
            "  AND AUTO_OPERATION.OBJECT_ID = FAMILY_REF.OBJECT_ID AND FAMILY_DEBIT_ACC.OBJECT_ID = FAMILY_REF.REFERENCE " +
            "  AND AUTO_OPERATION.OBJECT_ID = USERS_REF.OBJECT_ID AND USERS.OBJECT_ID = USERS_REF.REFERENCE " +
            "  AND DAY_OF_MONTH.ATTR_ID = ? AND AMOUNT.ATTR_ID = 56 " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND EMAIL.ATTR_ID = 3 AND USER_NAME.ATTR_ID = 5 " +
            "  AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND EMAIL.OBJECT_ID = USERS.OBJECT_ID AND USER_NAME.OBJECT_ID = USERS.OBJECT_ID";

    String GET_ALL_TODAY_AO_INCOME = "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, DEBIT_ACCOUNT.OBJECT_ID AS DEBIT_ID, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, " +
            "  LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION " +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS DEBIT_ACCOUNT, LISTS, ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES, " +
            "  OBJREFERENCE, ATTRIBUTES DAY_OF_MONTH " +
            "WHERE DEBIT_ACCOUNT.OBJECT_ID = ? AND DAY_OF_MONTH.ATTR_ID = 67 " +
            "  AND DATES.DATE_VALUE = TRUNC(CURRENT_DATE) " +
            "  AND AUTO_OPERATION.OBJECT_ID = OBJREFERENCE.OBJECT_ID AND DEBIT_ACCOUNT.OBJECT_ID = OBJREFERENCE.REFERENCE " +
            "  AND AMOUNT.ATTR_ID = 56 AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 67 " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "UNION ALL " +
            "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, DEBIT_ACCOUNT.OBJECT_ID AS DEBIT_ID, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, " +
            "  LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION " +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS DEBIT_ACCOUNT, LISTS, ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES, " +
            "  OBJREFERENCE, ATTRIBUTES DAY_OF_MONTH " +
            "WHERE DEBIT_ACCOUNT.OBJECT_ID = ? AND DAY_OF_MONTH.ATTR_ID = 68 " +
            "  AND DATES.DATE_VALUE = TRUNC(CURRENT_DATE) " +
            "  AND AUTO_OPERATION.OBJECT_ID = OBJREFERENCE.OBJECT_ID AND DEBIT_ACCOUNT.OBJECT_ID = OBJREFERENCE.REFERENCE " +
            "  AND AMOUNT.ATTR_ID = 56 AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID";


    String GET_ALL_TODAY_AO_EXPENSE = "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, DEBIT_ACCOUNT.OBJECT_ID AS DEBIT_ID, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, " +
            "  LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION" +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS DEBIT_ACCOUNT, LISTS, ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES," +
            "  OBJREFERENCE, ATTRIBUTES DAY_OF_MONTH " +
            "WHERE DEBIT_ACCOUNT.OBJECT_ID = ? AND DAY_OF_MONTH.ATTR_ID = 62 " +
            "  AND DATES.DATE_VALUE = TRUNC(CURRENT_DATE) " +
            "  AND AUTO_OPERATION.OBJECT_ID = OBJREFERENCE.OBJECT_ID AND DEBIT_ACCOUNT.OBJECT_ID = OBJREFERENCE.REFERENCE " +
            "  AND AMOUNT.ATTR_ID = 56 AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "UNION ALL " +
            "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, DEBIT_ACCOUNT.OBJECT_ID AS DEBIT_ID, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, " +
            "  LISTS.VALUE AS CATEGORY, DATES.DATE_VALUE AS DATE_OF_CREATION" +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS DEBIT_ACCOUNT, LISTS, ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES," +
            "  OBJREFERENCE, ATTRIBUTES DAY_OF_MONTH " +
            "WHERE DEBIT_ACCOUNT.OBJECT_ID = ? AND DAY_OF_MONTH.ATTR_ID = 63 " +
            "  AND DATES.DATE_VALUE = TRUNC(CURRENT_DATE) " +
            "  AND AUTO_OPERATION.OBJECT_ID = OBJREFERENCE.OBJECT_ID AND DEBIT_ACCOUNT.OBJECT_ID = OBJREFERENCE.REFERENCE " +
            "  AND AMOUNT.ATTR_ID = 56 AND CATEGORY.LIST_VALUE_ID = LISTS.LIST_VALUE_ID " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID";

    String GET_FAMILY_INCOME_AO = "SELECT AUTO_OPERATION.OBJECT_ID AS AO_OBJECT_ID, AUTO_OPERATION.NAME, " +
            "  FAMILY_DEBIT_ACC.OBJECT_ID AS FAMILY_DEBIT_ACC_ID, " +
            "  USERS.OBJECT_ID AS USER_ID, " +
            "  EMAIL.VALUE AS EMAIL, USER_NAME.VALUE AS USER_NAME, " +
            "  DAY_OF_MONTH.VALUE AS DAY_OF_MONTH, AMOUNT.VALUE AS AMOUNT, " +
            "  CATEGORY.LIST_VALUE_ID AS CATEGORY_ID, DATES.DATE_VALUE AS DATE_OF_CREATION " +
            "FROM OBJECTS AUTO_OPERATION, OBJECTS FAMILY_DEBIT_ACC, OBJECTS USERS, " +
            "  ATTRIBUTES AMOUNT, ATTRIBUTES CATEGORY, ATTRIBUTES DATES, ATTRIBUTES DAY_OF_MONTH, ATTRIBUTES EMAIL, " +
            "  ATTRIBUTES USER_NAME, OBJREFERENCE FAMILY_REF, OBJREFERENCE USERS_REF " +
            "WHERE FAMILY_REF.ATTR_ID = 65 AND USERS_REF.ATTR_ID = 66 " +
            "  AND AUTO_OPERATION.OBJECT_ID = ? " +
            "  AND AUTO_OPERATION.OBJECT_ID = FAMILY_REF.OBJECT_ID AND FAMILY_DEBIT_ACC.OBJECT_ID = FAMILY_REF.REFERENCE " +
            "  AND AUTO_OPERATION.OBJECT_ID = USERS_REF.OBJECT_ID AND USERS.OBJECT_ID = USERS_REF.REFERENCE " +
            "  AND DAY_OF_MONTH.ATTR_ID = 68 AND AMOUNT.ATTR_ID = 56 " +
            "  AND CATEGORY.ATTR_ID = 57 AND DATES.ATTR_ID = 58 " +
            "  AND EMAIL.ATTR_ID = 3 AND USER_NAME.ATTR_ID = 5 " +
            "  AND DAY_OF_MONTH.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND AMOUNT.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND CATEGORY.OBJECT_ID = AUTO_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = AUTO_OPERATION.OBJECT_ID " +
            "  AND EMAIL.OBJECT_ID = USERS.OBJECT_ID AND USER_NAME.OBJECT_ID = USERS.OBJECT_ID";

}
