package com.netcracker.dao;

import com.netcracker.models.CreditOperation;

import java.util.Collection;

public interface CreditOperationDao {
    CreditOperation getCreditOperationPersonal(Integer creditOperationId);

    CreditOperation getCreditOperationFamily(Integer creditOperationId);

    CreditOperation createFamilyCreditOperation(CreditOperation creditOperation, Integer creditFamilyAccountId, Integer userId);

    CreditOperation createPersonalCreditOperation(CreditOperation creditOperation, Integer creditPersonalAccountId);

    Collection<CreditOperation> getAllCreditOperationsByCreditFamilyId(Integer creditFamilyAccountId);

    Collection<CreditOperation> getAllCreditOperationsByCreditPersonalId(Integer creditPersonalAccountId);

    void deleteCreditOperation(Integer creditOperationId);

    String CREATE_CREDIT_OPERATION_PERSONAL = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 7, 'CREDIT_OPERATION_PERSONAL', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (40 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (41 /*DATE*/, OBJECTS_ID_S.CURRVAL, NULL, ?, NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (37, OBJECTS_ID_S.CURRVAL, ? /*REFERENCE TO CREDIT_ACC_PERSONAL*/) " + "SELECT * FROM DUAL";

    String CREATE_CREDIT_OPERATION_FAMILY = "INSERT ALL " +
            "INTO OBJECTS (OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION) " +
            "VALUES (OBJECTS_ID_S.NEXTVAL, NULL, 18, 'CREDIT_OPERATION_FAMILY', NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (40 /*AMOUNT*/, OBJECTS_ID_S.CURRVAL, ? /*AMOUNT*/, NULL, NULL) " +
            "INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID) " +
            "VALUES (41 /*DATE*/, OBJECTS_ID_S.CURRVAL, NULL, ?, NULL) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (38, OBJECTS_ID_S.CURRVAL, ? /*REFERENCE TO CREDIT_ACC_FAMILY*/) " +
            "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) " +
            "VALUES (39, OBJECTS_ID_S.CURRVAL, ? /*REFERENCE TO USER*/) " + "SELECT * FROM DUAL";

    String GET_CREDIT_OPERATION_PERSONAL =
            "SELECT CREDIT_ACC_PERSONAL.OBJECT_ID AS CREDIT_ACC_PERSONAL_ID, CREDIT_ACC_NAME.VALUE AS CREDIT_ACC_NAME, " +
                    "  CREDIT_OPERATION.OBJECT_ID AS OPERATION_ID, CREDIT_OPERATION.NAME AS OPERATION_NAME, " +
                    "  AMOUNT.VALUE AS AMOUNT, DATES.DATE_VALUE AS DATE_VALUE " +
                    "FROM OBJECTS CREDIT_ACC_PERSONAL, OBJECTS CREDIT_OPERATION, ATTRIBUTES CREDIT_ACC_NAME, " +
                    "  ATTRIBUTES AMOUNT, ATTRIBUTES DATES, OBJREFERENCE CREDIT_ACC_REF_USER " +
                    "WHERE CREDIT_ACC_REF_USER.ATTR_ID = 37 AND CREDIT_OPERATION.OBJECT_ID = ? " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = CREDIT_ACC_REF_USER.OBJECT_ID " +
                    "  AND CREDIT_ACC_PERSONAL.OBJECT_ID = CREDIT_ACC_REF_USER.REFERENCE " +
                    "  AND CREDIT_ACC_NAME.ATTR_ID = 30 AND AMOUNT.ATTR_ID = 40 AND DATES.ATTR_ID = 41 " +
                    "  AND CREDIT_ACC_NAME.OBJECT_ID = CREDIT_ACC_PERSONAL.OBJECT_ID " +
                    "  AND AMOUNT.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID";

    String GET_CREDIT_OPERATION_FAMILY =
            "SELECT CREDIT_ACC_FAMILY.OBJECT_ID AS CREDIT_ID_FAMILY, ACC_PERSONAL.OBJECT_ID AS ID_USER, " +
                    "  CREDIT_ACC_NAME.VALUE AS CREDIT_ACC_NAME, CREDIT_OPERATION.OBJECT_ID AS OPERATION_ID, " +
                    "  CREDIT_OPERATION.NAME AS OPERATION_NAME, AMOUNT.VALUE AS AMOUNT, DATES.DATE_VALUE AS DATE_VALUE " +
                    "FROM OBJECTS CREDIT_ACC_FAMILY, OBJECTS ACC_PERSONAL, OBJECTS CREDIT_OPERATION, ATTRIBUTES CREDIT_ACC_NAME, " +
                    "  ATTRIBUTES AMOUNT, ATTRIBUTES DATES, OBJREFERENCE ACC_REF_USER, OBJREFERENCE CREDIT_ACC_REF_FAMILY " +
                    "WHERE CREDIT_OPERATION.OBJECT_ID = ? " +
                    "  AND CREDIT_ACC_REF_FAMILY.ATTR_ID = 38 AND ACC_REF_USER.ATTR_ID = 39 " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = CREDIT_ACC_REF_FAMILY.OBJECT_ID " +
                    "  AND CREDIT_ACC_FAMILY.OBJECT_ID = CREDIT_ACC_REF_FAMILY.REFERENCE " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = ACC_REF_USER.OBJECT_ID " +
                    "  AND ACC_PERSONAL.OBJECT_ID = ACC_REF_USER.REFERENCE " +
                    "  AND CREDIT_ACC_NAME.ATTR_ID = 30 AND AMOUNT.ATTR_ID = 40 AND DATES.ATTR_ID = 41 " +
                    "  AND CREDIT_ACC_NAME.OBJECT_ID = CREDIT_ACC_FAMILY.OBJECT_ID " +
                    "  AND AMOUNT.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID";

    String DELETE_FROM_OBJECTS = "DELETE FROM OBJECTS WHERE OBJECT_ID = ?";
    String DELETE_FROM_ATTRIBUTES = "DELETE FROM ATTRIBUTES WHERE OBJECT_ID = ?";
    String DELETE_FROM_OBJREFERENCE = "DELETE FROM OBJREFERENCE WHERE OBJECT_ID = ?";

    String GET_ALL_CREDIT_OPERATIONS_PERSONAL =
            "SELECT CREDIT_ACC_PERSONAL.OBJECT_ID AS CREDIT_ACC_PERSONAL_ID, CREDIT_ACC_NAME.VALUE AS CREDIT_ACC_NAME, " +
                    "  CREDIT_OPERATION.OBJECT_ID AS OPERATION_ID, CREDIT_OPERATION.NAME AS OPERATION_NAME, " +
                    "  AMOUNT.VALUE AS AMOUNT, DATES.DATE_VALUE AS DATE_VALUE " +
                    "FROM OBJECTS CREDIT_ACC_PERSONAL, OBJECTS CREDIT_OPERATION, ATTRIBUTES CREDIT_ACC_NAME, " +
                    "  ATTRIBUTES AMOUNT, ATTRIBUTES DATES, OBJREFERENCE CREDIT_ACC_REF_USER " +
                    "WHERE CREDIT_ACC_PERSONAL.OBJECT_ID = ? AND CREDIT_ACC_REF_USER.ATTR_ID = 37 " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = CREDIT_ACC_REF_USER.OBJECT_ID " +
                    "  AND CREDIT_ACC_PERSONAL.OBJECT_ID = CREDIT_ACC_REF_USER.REFERENCE " +
                    "  AND CREDIT_ACC_NAME.ATTR_ID = 30 AND AMOUNT.ATTR_ID = 40 AND DATES.ATTR_ID = 41 " +
                    "  AND CREDIT_ACC_NAME.OBJECT_ID = CREDIT_ACC_PERSONAL.OBJECT_ID " +
                    "  AND AMOUNT.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID";

    String GET_ALL_CREDIT_OPERATIONS_FAMILY =
            "SELECT CREDIT_ACC_FAMILY.OBJECT_ID AS CREDIT_ID_FAMILY, ACC_PERSONAL.OBJECT_ID AS ID_USER, " +
                    "  CREDIT_ACC_NAME.VALUE AS CREDIT_ACC_NAME, CREDIT_OPERATION.OBJECT_ID AS OPERATION_ID, " +
                    "  CREDIT_OPERATION.NAME AS OPERATION_NAME, AMOUNT.VALUE AS AMOUNT, DATES.DATE_VALUE AS DATE_VALUE " +
                    "FROM OBJECTS CREDIT_ACC_FAMILY, OBJECTS ACC_PERSONAL, OBJECTS CREDIT_OPERATION, ATTRIBUTES CREDIT_ACC_NAME, " +
                    "  ATTRIBUTES AMOUNT, ATTRIBUTES DATES, OBJREFERENCE ACC_REF_USER, OBJREFERENCE CREDIT_ACC_REF_FAMILY " +
                    "WHERE CREDIT_ACC_FAMILY.OBJECT_ID = ? " +
                    "  AND CREDIT_ACC_REF_FAMILY.ATTR_ID = 38 AND ACC_REF_USER.ATTR_ID = 39 " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = CREDIT_ACC_REF_FAMILY.OBJECT_ID " +
                    "  AND CREDIT_ACC_FAMILY.OBJECT_ID = CREDIT_ACC_REF_FAMILY.REFERENCE " +
                    "  AND CREDIT_OPERATION.OBJECT_ID = ACC_REF_USER.OBJECT_ID " +
                    "  AND ACC_PERSONAL.OBJECT_ID = ACC_REF_USER.REFERENCE " +
                    "  AND CREDIT_ACC_NAME.ATTR_ID = 30 AND AMOUNT.ATTR_ID = 40 AND DATES.ATTR_ID = 41 " +
                    "  AND CREDIT_ACC_NAME.OBJECT_ID = CREDIT_ACC_FAMILY.OBJECT_ID " +
                    "  AND AMOUNT.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID AND DATES.OBJECT_ID = CREDIT_OPERATION.OBJECT_ID";
}
