package com.netcracker.dao;

import com.netcracker.models.*;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.Collection;
import java.util.List;

public interface MonthReportDao {


    void createPersonalMonthReport(MonthReport monthReport, BigInteger id);

    void createFamilyMonthReport(MonthReport monthReport, BigInteger id);

    Collection<MonthReport> getMonthReportsByFamilyAccountId(BigInteger id);

    Collection<MonthReport> getMonthReportsByPersonalAccountId(BigInteger id);



    void createCategoryIncomePersonalReport();

    void createCategoryIncomeFamilyReport();

    void createCategoryExpensePersonalReport();

    void createCategoryExpenseFamilyReport();

    Collection<CategoryIncomeReport> getCategoryIncomePersonalReport(BigInteger id);

    Collection<CategoryIncomeReport> getCategoryIncomeFamilyReport(BigInteger id);

    Collection<CategoryExpenseReport> getCategoryExpensePersonalReport(BigInteger id);

    Collection<CategoryExpenseReport> getCategoryExpenseFamilyReport(BigInteger id);



    String CREATE_PERSONAL_MONTH_REPORT = "INSERT ALL" +
            " INTO OBJECTS(OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL, null,3, 'Personal report', 'Personal report')" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(12, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE) VALUES(15, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE) VALUES(16, OBJECTS_ID_S.CURRVAL,?)" +
            " INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (10,OBJECTS_ID_S.CURRVAL,?)"+
            " SELECT * FROM DUAL";
    String CREATE_FAMILY_MONTH_REPORT = "INSERT ALL" +
            " INTO OBJECTS(OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL, null,14, 'Family report', 'family report')" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(12, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(14, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE) VALUES(15, OBJECTS_ID_S.CURRVAL, ?)" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, DATE_VALUE) VALUES(16, OBJECTS_ID_S.CURRVAL,?)" +
            " INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (11,OBJECTS_ID_S.CURRVAL,?)" +
            " SELECT * FROM DUAL";

    String GET_MONTH_REPORT_BY_FAMILY_ACCOUNT_ID = "SELECT O.OBJECT_ID AS MONTH_REPORT_ID, TOTALINCOME.VALUE AS INCOME, " +
            "  TOTALEXPENSE.VALUE AS EXPENSE, BALANCE.VALUE AS BALANCE, " +
            "  DATE_FROM.DATE_VALUE AS DATE_FROM, DATE_TO.DATE_VALUE AS DATE_TO " +
            "  FROM ATTRIBUTES TOTALINCOME, ATTRIBUTES TOTALEXPENSE, " +
            "  ATTRIBUTES BALANCE, ATTRIBUTES DATE_FROM, ATTRIBUTES DATE_TO, OBJREFERENCE OBJ, OBJECTS O " +
            "  WHERE OBJ.ATTR_ID = 11 AND O.OBJECT_ID = OBJ.OBJECT_ID AND OBJ.REFERENCE = ? " +
            "  AND TOTALINCOME.OBJECT_ID = O.OBJECT_ID AND TOTALINCOME.ATTR_ID = 12 /*TOTALINCOME*/ " +
            "  AND TOTALEXPENSE.OBJECT_ID = O.OBJECT_ID AND TOTALEXPENSE.ATTR_ID = 13 /*TOTALEXPENSE*/ " +
            "  AND BALANCE.OBJECT_ID = O.OBJECT_ID AND BALANCE.ATTR_ID = 14 /*BALANCE*/ " +
            "  AND DATE_FROM.OBJECT_ID = O.OBJECT_ID AND  DATE_FROM.ATTR_ID = 15 " +
            "  AND DATE_TO.OBJECT_ID = O.OBJECT_ID AND DATE_TO.ATTR_ID = 16";

    String GET_MONTH_REPORT_BY_PERSONAL_ACCOUNT_ID = "SELECT O.OBJECT_ID AS MONTH_REPORT_ID, TOTALINCOME.VALUE AS INCOME," +
            " TOTALEXPENSE.VALUE AS EXPENSE, BALANCE.VALUE AS BALANCE," +
            " DATE_FROM.DATE_VALUE AS DATE_FROM, DATE_TO.DATE_VALUE AS DATE_TO" +
            " FROM ATTRIBUTES TOTALINCOME, ATTRIBUTES TOTALEXPENSE," +
            " ATTRIBUTES BALANCE, ATTRIBUTES DATE_FROM, ATTRIBUTES DATE_TO, OBJREFERENCE OBJ, OBJECTS O " +
            " WHERE OBJ.ATTR_ID = 10 AND O.OBJECT_ID = OBJ.OBJECT_ID AND OBJ.REFERENCE = ?" +
            " AND TOTALINCOME.OBJECT_ID = O.OBJECT_ID AND TOTALINCOME.ATTR_ID = 12 /*TOTALINCOME*/" +
            " AND TOTALEXPENSE.OBJECT_ID = O.OBJECT_ID AND TOTALEXPENSE.ATTR_ID = 13 /*TOTALEXPENSE*/" +
            " AND BALANCE.OBJECT_ID = O.OBJECT_ID AND BALANCE.ATTR_ID = 14 /*BALANCE*/" +
            " AND DATE_FROM.OBJECT_ID = O.OBJECT_ID AND  DATE_FROM.ATTR_ID = 15" +
            " AND DATE_TO.OBJECT_ID = O.OBJECT_ID AND DATE_TO.ATTR_ID = 16";


    String CREATE_CATEGORY_INCOME_PERSONAL_REPORT_BY_ID = "INSERT ALL" +
            " INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL,NULL,4,'CAT_REP_PER_INC','Category report personal income') " +
            " INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (17,6,?) /* reference to personal report*/" +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, LIST_VALUE_ID) VALUES(20, OBJECTS_ID_S.CURRVAL, ?) /* category */ " +
            " INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(21, OBJECTS_ID_S.CURRVAL, ?) /* amount */";

    String CREATE_CATEGORY_INCOME_FAMILY_REPORT_BY_ID = "INSERT ALL" +
            "  INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL,NULL,15,'CAT_REP_FAM_INC','Catery report family income')" +
            "  INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (18, OBJECTS_ID_S.CURRVAL,?) /* reference to family report */" +
            "  INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (19,OBJECTS_ID_S.CURRVAL,?) /* reference to participant in family*/" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, LIST_VALUE_ID) VALUES(20, OBJECTS_ID_S.CURRVAL, ?) /* category */" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(21, OBJECTS_ID_S.CURRVAL, ?) /* amount */" +
            "  SELECT * FROM DUAL";

    String CREATE_CATEGORY_EXPENSE_PERSONAL_REPORT_BY_ID = "INSERT ALL" +
            "  INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL,NULL,5,'CAT_REP_PER_EXP','Category report personal expense')" +
            "  INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (22,OBJECTS_ID_S.CURRVAL,?) /* reference to personal report */" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, LIST_VALUE_ID) VALUES(25, OBJECTS_ID_S.CURRVAL, ?) /* category */" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(26, OBJECTS_ID_S.CURRVAL, ?); /* amount */" +
            "  SELECT * FROM DUAL";

    String CREATE_CATEGORY_EXPENSE_FAMILY_REPORT_BY_ID = "INSERT ALL" +
            "  INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL,NULL,16,'CAT_REP_FAM_EXP','Category report family expense')" +
            "  INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (23,OBJECTS_ID_S.CURRVAL,?) /* reference to family  */" +
            "  INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (24,OBJECTS_ID_S.CURRVAL,?) /* reference to participant in family */" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, LIST_VALUE_ID) VALUES(25, OBJECTS_ID_S.CURRVAL, ?) /* category */" +
            "  INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE) VALUES(26, OBJECTS_ID_S.CURRVAL, ?); /* amount */" +
            "  SELECT * FROM DUAL";


    String GET_CATEGORY_INCOME_PERSONAL_REPORT_BY_ID = "SELECT O.OBJECT_ID AS CATEGORY_INCOME_REPORT,  SUMM.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY" +
            "  FROM ATTRIBUTES SUMM,  ATTRIBUTES CATEGORY, OBJECTS O, OBJREFERENCE REF" +
            "  WHERE O.OBJECT_TYPE_ID =  4 AND REF.ATTR_ID = 17 AND O.OBJECT_ID = REF.OBJECT_ID AND REF.REFERENCE = ?" +
            "  AND SUMM.OBJECT_ID = O.OBJECT_ID AND SUMM.ATTR_ID = 21 /* amount*/" +
            "  AND CATEGORY.OBJECT_ID = O.OBJECT_ID AND CATEGORY.ATTR_ID = 20; /* category*/";

    String GET_CATEGORY_INCOME_FAMILY_REPORT_BY_ID = "SELECT O.OBJECT_ID AS CATEGORY_INCOME_REPORT,  SUMM.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY" +
            "   FROM ATTRIBUTES SUMM,  ATTRIBUTES CATEGORY, OBJECTS O, OBJREFERENCE REF" +
            "   WHERE  AND REF.ATTR_ID = 18 AND O.OBJECT_ID = REF.OBJECT_ID AND REF.REFERENCE = ?" +
            "   AND SUMM.OBJECT_ID = O.OBJECT_ID AND SUMM.ATTR_ID = 20 /* amount*/" +
            "   AND CATEGORY.OBJECT_ID = O.OBJECT_ID AND CATEGORY.ATTR_ID = 21;";

    String GET_CATEGORY_EXPENSE_PERSONAL_REPORT_BY_ID = "SELECT O.OBJECT_ID AS CATEGORY_INCOME_REPORT,  SUMM.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY" +
            " FROM ATTRIBUTES SUMM,  ATTRIBUTES CATEGORY, OBJECTS O, OBJREFERENCE REF" +
            " WHERE  AND REF.ATTR_ID = 22 AND O.OBJECT_ID = REF.OBJECT_ID AND REF.REFERENCE = ?" +
            " AND SUMM.OBJECT_ID = O.OBJECT_ID AND SUMM.ATTR_ID = 26 /* amount*/" +
            " AND CATEGORY.OBJECT_ID = O.OBJECT_ID AND CATEGORY.ATTR_ID = 25; /* category*/";

    String GET_CATEGORY_EXPENSE_FAMILY_REPORT_BY_ID = "SELECT O.OBJECT_ID AS CATEGORY_INCOME_REPORT,  SUMM.VALUE AS AMOUNT, CATEGORY.LIST_VALUE_ID AS CATEGORY" +
            "  FROM ATTRIBUTES SUMM,  ATTRIBUTES CATEGORY, OBJECTS O, OBJREFERENCE REF" +
            "  WHERE  AND REF.ATTR_ID = 23 AND O.OBJECT_ID = REF.OBJECT_ID AND REF.REFERENCE = ?" +
            "  AND SUMM.OBJECT_ID = O.OBJECT_ID AND SUMM.ATTR_ID = 26 /* amount*/" +
            "  AND CATEGORY.OBJECT_ID = O.OBJECT_ID AND CATEGORY.ATTR_ID = 25; /* category*/";

}
