package com.netcracker.dao;

import com.netcracker.models.User;

import java.math.BigInteger;

public interface UserDao {

    User createUser(User user);


    User getUserById(BigInteger id);


    User getUserByEmail(String login);


    void updateUserPasswordById(BigInteger id, String newPassword);


    void updateUserStatus(BigInteger id, BigInteger newStatus);


    void updateEmail(BigInteger id, String newEmail);


    String CREATE_USER = "INSERT ALL  " +
            "INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (OBJECTS_ID_S.NEXTVAL,NULL,1,'user'||OBJECTS_ID_S.CURRVAL,NULL) " +
            "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (3,OBJECTS_ID_S.CURRVAL,?,NULL,NULL /* MAIL*/) " +
            "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (4,OBJECTS_ID_S.CURRVAL,?,NULL,NULL /* PASSWORD*/) " +
            "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (5,OBJECTS_ID_S.CURRVAL,?,NULL,NULL /* NAME*/) " +
            "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (6,OBJECTS_ID_S.CURRVAL,NULL,NULL,? /* IS_ACTIVE*/) " +
            "SELECT * " +
            "FROM Dual";

    String GET_USER_BY_LOGIN = "SELECT DISTINCT US.NAME OBJ_NAME , EMP_NAME.VALUE NAME,  US_EMAIL.VALUE EMAIL,US.OBJECT_ID AS USER_ID, " +
            "PASSWORD.VALUE AS PASSWORD, EMP_STATUS.LIST_VALUE_ID AS IS_ACTIVE, " +
            "(SELECT PER_ACC.REFERENCE FROM OBJREFERENCE PER_ACC WHERE US.OBJECT_ID  = PER_ACC.OBJECT_ID AND PER_ACC.ATTR_ID = 1) as PER_DEB_ACC1, " +
            "(SELECT FAM_ACC.REFERENCE FROM OBJREFERENCE FAM_ACC WHERE US.OBJECT_ID  = FAM_ACC.OBJECT_ID AND FAM_ACC.ATTR_ID = 2) as FAM_DEB_ACC1 " +
            "FROM OBJECTS US, ATTRIBUTES US_EMAIL, ATTRIBUTES PASSWORD, ATTRIBUTES EMP_STATUS, attributes EMP_NAME " +
            "WHERE US_EMAIL.VALUE  = ? " +
            "AND US.OBJECT_TYPE_ID = 1 " +
            "AND US.OBJECT_ID = US_EMAIL.OBJECT_ID " +
            "AND PASSWORD.ATTR_ID = 4  /* PASSWORD*/ " +
            "AND PASSWORD.OBJECT_ID = US.OBJECT_ID " +
            "AND EMP_STATUS.ATTR_ID = 6  /* IS_ACTIVE*/ " +
            "AND EMP_STATUS.OBJECT_ID = US.OBJECT_ID " +
            "AND EMP_NAME.ATTR_ID = 5  /* NAME*/ " +
            "AND EMP_NAME.OBJECT_ID = US.OBJECT_ID ";


    String GET_USER_BY_USER_ID = "SELECT DISTINCT  US.NAME OBJ_NAME , EMP_NAME.VALUE NAME,  US_EMAIL.VALUE EMAIL,US.OBJECT_ID AS USER_ID, " +
            "PASSWORD.VALUE AS PASSWORD, EMP_STATUS.LIST_VALUE_ID AS IS_ACTIVE, " +
            "(SELECT PER_ACC.REFERENCE FROM OBJREFERENCE PER_ACC WHERE US.OBJECT_ID  = PER_ACC.OBJECT_ID AND PER_ACC.ATTR_ID = 1) as PER_DEB_ACC1, " +
            "(SELECT FAM_ACC.REFERENCE FROM OBJREFERENCE FAM_ACC WHERE US.OBJECT_ID  = FAM_ACC.OBJECT_ID AND FAM_ACC.ATTR_ID = 2) as FAM_DEB_ACC1 " +
            "FROM OBJECTS US, ATTRIBUTES US_EMAIL, ATTRIBUTES PASSWORD, ATTRIBUTES EMP_STATUS, attributes EMP_NAME " +
            "WHERE US.OBJECT_ID  = ? " +
            "AND US.OBJECT_TYPE_ID = 1 " +
            "AND US_EMAIL.ATTR_ID = 3 /* MAIL*/  " +
            "AND US.OBJECT_ID = US_EMAIL.OBJECT_ID " +
            "AND PASSWORD.ATTR_ID = 4  /* PASSWORD*/ " +
            "AND PASSWORD.OBJECT_ID = US.OBJECT_ID " +
            "AND EMP_STATUS.ATTR_ID = 6  /* IS_ACTIVE*/ " +
            "AND EMP_STATUS.OBJECT_ID = US.OBJECT_ID " +
            "AND EMP_NAME.ATTR_ID = 5  /* NAME*/ " +
            "AND EMP_NAME.OBJECT_ID = US.OBJECT_ID ";

    String UPDATE_PASSWORD = "UPDATE ATTRIBUTES " +
            "SET VALUE = ? " +
            "WHERE OBJECT_ID = ?  " +
            " AND ATTR_ID = 4 /* PASSWORD*/ ";


    String UPDATE_STATUS = "UPDATE ATTRIBUTES " +
            "SET LIST_VALUE_ID = ? " +
            "WHERE OBJECT_ID = ?  " +
            " AND ATTR_ID = 6 /*IS_ACTIVE */ ";


    String UPDATE_EMAIL = "UPDATE ATTRIBUTES " +
            "SET VALUE = ? " +
            "WHERE OBJECT_ID = ?  " +
            " AND ATTR_ID = 3 /* MAIL*/ ";
}
