
language: java
java:
  - 1.8.0_231
install: true
script:
  - mvn clean install

branches:
  only:
    - master
deploy:
  provider: heroku
  app: teamexample
  api_key:
    secure: 3f72c6ba-31d0-4d50-a2ef-33ed37ae61d4
