language: java
java:
  - 1.8.0_231
install: true
cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

branches:
  only:
    - master
deploy:
  provider: heroku
  app: teamexample
  api_key:
    secure: 3f72c6ba-31d0-4d50-a2ef-33ed37ae61d4
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}