
language: java
java:
  - 1.8.0_231
install: true
script:
  - mvn clean install

branches:
  only:
    - master
deploy:
  provider: heroku
  app: teamexample
  api_key:
    secure: ab4919bf-99db-49e4-a9fa-e12fa9ebfb32
